# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Home CICD

on:
  push:
    branches: [ "main" ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Build and archive
      run: npm run build
      env:
        CI: false

    - name: Copy files to remote server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        port: ${{ secrets.VM_PORT }}
        key: ${{ secrets.VM_PRIVATE_KEY_ARCHBOX }}
        source: "build/"
        target: "/var/www/html/"
        
    - name: SSH into server and restart Apache
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        port: ${{ secrets.VM_PORT }}
        key: ${{ secrets.VM_PRIVATE_KEY_ARCHBOX }}
        script: |
          sshpass -p ${{ secrets.SUDO_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} 'echo ${{ secrets.SUDO_PASSWORD }} | sudo -S systemctl restart apache2'
              
