# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Home CICD

on:
  push:
    branches: [ "main" ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm install
    - name: Build and archive
      run: |
        npm run build
        mkdir -p deploy
        cp -r build/* deploy/
        tar -czf deploy.tar.gz deploy
    - name: Deploy to VM
      # You may pin to the exact commit or the version.
      # uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_PRIVATE_KEY }}
        script: |
          mkdir -p /var/www/html
          tar -xzf deploy.tar.gz -C /var/www/html
              
